In [ ]:
import pandas as pd
import numpy as np
from collections import Counter

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler, RobustScaler
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest, f_classif


from sklearn.model_selection import PredefinedSplit
from sklearn.model_selection import GridSearchCV
from sklearn.utils.class_weight import compute_class_weight


from catboost import CatBoostClassifier


from sklearn.metrics import accuracy_score, f1_score

In [3]:
train = pd.read_csv(r"C:\Users\Gimly\Desktop\data sience\date\train_bdimo", sep='\t').drop(['id'], axis =1)
test = pd.read_csv(r"C:\Users\Gimly\Desktop\data sience\date\test_bdimo", sep='\t')

In [12]:
le =LabelEncoder()
train['y'] = le.fit_transform(train.y)
train

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,...,x992,x993,x994,x995,x996,x997,x998,x999,x1000,y
0,80.000000,60.793651,-10.000000,-20.000000,-10.000000,150.000000,385.874377,-510.000000,53.733647,-10.000,...,20.0,60.000000,-10.000000,50.000000,-1260.99042,-50.000000,-18.394139,-3860.0,-270.000000,1
1,70.000000,20.000000,-20.000000,-7.420088,-10.000000,123.654212,360.000000,-440.000000,-400.000000,-4.158,...,20.0,40.226641,-90.000000,50.000000,-1260.99042,-60.000000,0.000000,-3250.0,-750.000000,1
2,80.000000,60.793651,20.000000,-10.000000,10.000000,123.654212,190.000000,-500.000000,880.000000,-4.158,...,10.0,40.226641,16.217575,60.000000,-1310.00000,-40.000000,0.000000,-3410.0,-630.000000,0
3,60.000000,60.793651,5.645222,-40.000000,-2.613335,123.654212,580.000000,-415.535701,-200.000000,-10.000,...,20.0,60.000000,40.000000,60.000000,-1260.99042,-50.000000,-18.394139,-3020.0,-650.198583,1
4,70.000000,60.793651,5.645222,-10.000000,0.000000,230.000000,385.874377,30.000000,390.000000,0.000,...,20.0,40.226641,-60.000000,48.734345,-1410.00000,-50.000000,-40.000000,-3500.0,-420.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,70.000000,80.000000,5.645222,0.000000,0.000000,180.000000,180.000000,-600.000000,590.000000,-4.158,...,20.0,60.000000,16.217575,40.000000,-1320.00000,-40.000000,-20.000000,-3510.0,-650.198583,0
19996,70.000000,90.000000,5.645222,0.000000,0.000000,140.000000,540.000000,-380.000000,53.733647,-10.000,...,10.0,40.226641,-40.000000,50.000000,-1260.99042,-50.806794,-20.000000,-3420.0,-510.000000,0
19997,60.000000,60.793651,5.645222,40.000000,10.000000,180.000000,320.000000,-415.535701,53.733647,-4.158,...,10.0,40.226641,16.217575,48.734345,-1050.00000,-50.806794,-18.394139,-3250.0,-520.000000,0
19998,71.792725,60.793651,-30.000000,0.000000,-2.613335,200.000000,300.000000,-415.535701,53.733647,0.000,...,10.0,70.000000,16.217575,40.000000,-1260.99042,-60.000000,-40.000000,-3500.0,-850.000000,0
19999,80.000000,70.000000,5.645222,-20.000000,0.000000,130.000000,660.000000,-190.000000,-400.000000,-4.158,...,20.0,10.000000,80.000000,50.000000,-1400.00000,-50.000000,-18.394139,-3490.0,-740.000000,1

In [13]:
X = train.drop(['y'], axis=1)
X

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,...,x991,x992,x993,x994,x995,x996,x997,x998,x999,x1000
0,80.000000,60.793651,-10.000000,-20.000000,-10.000000,150.000000,385.874377,-510.000000,53.733647,-10.000,...,50.000000,20.0,60.000000,-10.000000,50.000000,-1260.99042,-50.000000,-18.394139,-3860.0,-270.000000
1,70.000000,20.000000,-20.000000,-7.420088,-10.000000,123.654212,360.000000,-440.000000,-400.000000,-4.158,...,51.877524,20.0,40.226641,-90.000000,50.000000,-1260.99042,-60.000000,0.000000,-3250.0,-750.000000
2,80.000000,60.793651,20.000000,-10.000000,10.000000,123.654212,190.000000,-500.000000,880.000000,-4.158,...,50.000000,10.0,40.226641,16.217575,60.000000,-1310.00000,-40.000000,0.000000,-3410.0,-630.000000
3,60.000000,60.793651,5.645222,-40.000000,-2.613335,123.654212,580.000000,-415.535701,-200.000000,-10.000,...,50.000000,20.0,60.000000,40.000000,60.000000,-1260.99042,-50.000000,-18.394139,-3020.0,-650.198583
4,70.000000,60.793651,5.645222,-10.000000,0.000000,230.000000,385.874377,30.000000,390.000000,0.000,...,50.000000,20.0,40.226641,-60.000000,48.734345,-1410.00000,-50.000000,-40.000000,-3500.0,-420.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,70.000000,80.000000,5.645222,0.000000,0.000000,180.000000,180.000000,-600.000000,590.000000,-4.158,...,51.877524,20.0,60.000000,16.217575,40.000000,-1320.00000,-40.000000,-20.000000,-3510.0,-650.198583
19996,70.000000,90.000000,5.645222,0.000000,0.000000,140.000000,540.000000,-380.000000,53.733647,-10.000,...,51.877524,10.0,40.226641,-40.000000,50.000000,-1260.99042,-50.806794,-20.000000,-3420.0,-510.000000
19997,60.000000,60.793651,5.645222,40.000000,10.000000,180.000000,320.000000,-415.535701,53.733647,-4.158,...,60.000000,10.0,40.226641,16.217575,48.734345,-1050.00000,-50.806794,-18.394139,-3250.0,-520.000000
19998,71.792725,60.793651,-30.000000,0.000000,-2.613335,200.000000,300.000000,-415.535701,53.733647,0.000,...,50.000000,10.0,70.000000,16.217575,40.000000,-1260.99042,-60.000000,-40.000000,-3500.0,-850.000000
19999,80.000000,70.000000,5.645222,-20.000000,0.000000,130.000000,660.000000,-190.000000,-400.000000,-4.158,...,50.000000,20.0,10.000000,80.000000,50.000000,-1400.00000,-50.000000,-18.394139,-3490.0,-740.000000

In [14]:
# kbest = SelectKBest(f_classif, k=10)
# X = pd.DataFrame(data=kbest.fit_transform(X, train.y))
# X

In [15]:
# pca = PCA(n_components=900)
# X = pd.DataFrame(data=pca.fit_transform(X))
# X

In [16]:
scaler = StandardScaler()
# scaler = MinMaxScaler((0, 1))
# scaler = RobustScaler()
X = pd.DataFrame(scaler.fit_transform(X))
X

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
0,1.381947,0.000000,-4.567135e-01,-0.458116,-7.649544e-01,0.304677,0.000000,-6.460535e-01,0.000000,-1.439699,...,-5.826274e-01,1.032660,1.209963,-0.435156,1.318085e-01,0.000000,1.287858e-01,2.880684e-16,-1.517613,1.552813
1,-0.301860,-1.227218,-7.486323e-01,0.000000,-7.649544e-01,0.000000,-0.198807,-1.673145e-01,-0.879830,0.000000,...,-4.409868e-15,1.032660,0.000000,-1.762987,1.318085e-01,0.000000,-1.467480e+00,1.491471e+00,-0.038504,-0.407611
2,1.381947,0.000000,4.190430e-01,-0.093951,1.306222e+00,0.000000,-1.505011,-5.776622e-01,1.602204,0.000000,...,-5.826274e-01,-1.426701,0.000000,0.000000,1.173233e+00,-0.268038,1.725052e+00,1.491471e+00,-0.426467,0.082495
3,-1.985667,0.000000,-2.592760e-17,-1.186447,4.598936e-17,0.000000,1.491574,-3.887595e-16,-0.492012,-1.439699,...,-5.826274e-01,1.032660,1.209963,0.394738,1.173233e+00,0.000000,1.287858e-01,2.880684e-16,0.519192,0.000000
4,-0.301860,0.000000,-2.592760e-17,-0.093951,2.706340e-01,1.229841,0.000000,3.047076e+00,0.652050,1.024695,...,-5.826274e-01,1.032660,0.000000,-1.265051,7.399769e-16,-0.814949,1.287858e-01,-1.751891e+00,-0.644696,0.940181
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,-0.301860,0.577795,-2.592760e-17,0.270214,2.706340e-01,0.651613,-1.581846,-1.261575e+00,1.039868,0.000000,...,-4.409868e-15,1.032660,1.209963,0.000000,-9.096164e-01,-0.322730,1.725052e+00,-1.302097e-01,-0.668944,0.000000
19996,-0.301860,0.878631,-2.592760e-17,0.270214,2.706340e-01,0.189032,1.184232,2.430332e-01,0.000000,-1.439699,...,-4.409868e-15,-1.426701,0.000000,-0.933093,1.318085e-01,0.000000,1.134215e-15,-1.302097e-01,-0.450715,0.572601
19997,-1.985667,0.000000,-2.592760e-17,1.726874,1.306222e+00,0.651613,-0.506149,-3.887595e-16,0.000000,0.000000,...,2.520541e+00,-1.426701,0.000000,0.000000,7.399769e-16,1.153929,1.134215e-15,2.880684e-16,-0.038504,0.531759
19998,0.000000,0.000000,-1.040551e+00,0.270214,4.598936e-17,0.882904,-0.659820,-3.887595e-16,0.000000,1.024695,...,-5.826274e-01,-1.426701,1.821879,0.000000,-9.096164e-01,0.000000,-1.467480e+00,-1.751891e+00,-0.644696,-0.816032
19999,1.381947,0.276960,-2.592760e-17,-0.458116,2.706340e-01,0.073386,2.106258,1.542468e+00,-0.879830,0.000000,...,-5.826274e-01,1.032660,-1.849616,1.058653,1.318085e-01,-0.760258,1.287858e-01,2.880684e-16,-0.620449,-0.366768

In [ ]:
y = train['y']

In [ ]:
clf = CatBoostClassifier(iterations=10000, 
                           eval_metric='TotalF1',
                           depth=12, 
                           od_wait=500,
                           use_best_model=True,
                           task_type='CPU'
                           )

clf.fit(X, y, verbose=200)

Learning rate set to 0.023085
0:	learn: 0.8530758	test: 0.8457103	best: 0.8457103 (0)	total: 420ms	remaining: 1h 10m 3s
200:	learn: 0.9428672	test: 0.9197495	best: 0.9199913 (185)	total: 1m 1s	remaining: 49m 39s
400:	learn: 0.9558995	test: 0.9219282	best: 0.9229389 (358)	total: 1m 57s	remaining: 46m 57s
600:	learn: 0.9643133	test: 0.9230450	best: 0.9232658 (549)	total: 2m 53s	remaining: 45m 19s
800:	learn: 0.9730329	test: 0.9268795	best: 0.9273640 (784)	total: 3m 52s	remaining: 44m 28s
1000:	learn: 0.9783895	test: 0.9266373	best: 0.9273640 (784)	total: 4m 49s	remaining: 43m 22s
1200:	learn: 0.9829871	test: 0.9273838	best: 0.9279076 (1110)	total: 5m 46s	remaining: 42m 20s
1400:	learn: 0.9872707	test: 0.9276653	best: 0.9279076 (1110)	total: 6m 44s	remaining: 41m 20s
1600:	learn: 0.9914137	test: 0.9281694	best: 0.9286927 (1540)	total: 7m 42s	remaining: 40m 24s
1800:	learn: 0.9938609	test: 0.9284311	best: 0.9286927 (1540)	total: 8m 39s	remaining: 39m 25s
2000:	learn: 0.9958673	test: 0.9274231	best: 0.9289159 (1812)	total: 9m 36s	remaining: 38m 25s
2200:	learn: 0.9976222	test: 0.9271415	best: 0.9289159 (1812)	total: 10m 33s	remaining: 37m 26s
Stopped by overfitting detector  (500 iterations wait)

bestTest = 0.928915911
bestIteration = 1812

Shrink model to first 1813 iterations.

In [ ]:
X_pred = test.drop(['id'], axis=1)
# X_pred = kbest.transform(X_pred)
# X_pred = pca.transform(X_pred)
X_pred = scaler.transform(X_pred)
pred = clf.predict(X_pred)
pred

array([1, 0, 0, ..., 0, 0, 0])

In [24]:
test['y'] = le.inverse_transform(pred)
test

,id,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x992,x993,x994,x995,x996,x997,x998,x999,x1000,y
0,20001,70.000000,90.000000,-100.000000,-7.692767,-10.00000,122.507357,260.000000,-370.000000,-280.000000,...,15.8103,10.000000,140.000000,50.000000,-1260.440221,-60.00000,-18.293118,-3200.000000,-950.000000,P
1,20002,60.000000,40.000000,-40.000000,-20.000000,-10.00000,110.000000,330.000000,-412.937313,59.390404,...,20.0000,40.000000,15.435328,48.894787,-1220.000000,-50.00000,-18.293118,-3560.000000,-920.000000,N
2,20003,80.000000,60.000000,6.902077,-60.000000,0.00000,122.507357,360.000000,-540.000000,59.390404,...,20.0000,39.960365,100.000000,48.894787,-1170.000000,-50.00000,-10.000000,-3229.857769,-655.992307,N
3,20004,80.000000,90.000000,40.000000,10.000000,-2.52149,190.000000,490.000000,-380.000000,59.390404,...,20.0000,20.000000,-40.000000,40.000000,-1260.440221,-50.79482,-40.000000,-3229.857769,-655.992307,N
4,20005,80.000000,70.000000,40.000000,-7.692767,-2.52149,70.000000,470.000000,-340.000000,630.000000,...,10.0000,30.000000,20.000000,40.000000,-1700.000000,-60.00000,-20.000000,-3229.857769,-420.000000,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12340,32341,60.000000,60.830025,6.902077,20.000000,-2.52149,240.000000,430.000000,-412.937313,340.000000,...,10.0000,70.000000,50.000000,50.000000,-1390.000000,-50.79482,-10.000000,-2890.000000,-490.000000,N
12341,32342,71.693249,50.000000,-30.000000,0.000000,20.00000,80.000000,360.000000,-412.937313,-180.000000,...,15.8103,39.960365,15.435328,50.000000,-1260.440221,-50.00000,-18.293118,-3010.000000,-655.992307,N
12342,32343,70.000000,60.830025,30.000000,-7.692767,10.00000,170.000000,190.000000,-570.000000,310.000000,...,10.0000,20.000000,-150.000000,48.894787,-1260.440221,-50.00000,-18.293118,-3120.000000,-710.000000,N
12343,32344,70.000000,20.000000,-60.000000,-40.000000,-30.00000,210.000000,560.000000,-412.937313,-540.000000,...,15.8103,39.960365,-10.000000,60.000000,-1630.000000,-50.79482,-18.293118,-3700.000000,-570.000000,N
12344,32345,71.693249,40.000000,-30.000000,-7.692767,0.00000,50.000000,386.127404,-450.000000,59.390404,...,10.0000,39.960365,-50.000000,50.000000,-1260.440221,-50.00000,-20.000000,-3229.857769,-850.000000,N

In [25]:
sub = test[['id', 'y']]
sub

          id  y
0      20001  P
1      20002  N
2      20003  N
3      20004  N
4      20005  N
...      ... ..
12340  32341  N
12341  32342  N
12342  32343  N
12343  32344  N
12344  32345  N

[12345 rows x 2 columns]

In [ ]:
sub.to_csv('sub.tsv', sep='\t')